<?php

namespace AppBundle\Repository;

/**
 * AlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteRepository extends \Doctrine\ORM\EntityRepository
{
	public function countHistory(){

		$qb = $this->createQueryBuilder('alerte');
		$qb
			->select('COUNT(alerte.id)')
			->where('alerte.isOk = :p_isOk ')
			->setParameters(array('p_isOk'=>true));

        return $qb->getQuery()->getSingleScalarResult();
	}
}
