<?php

namespace AppBundle\Repository;

/**
 * AssembleeGeneraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssembleeGeneraleRepository extends \Doctrine\ORM\EntityRepository
{
}
