<?php

namespace AppBundle\Repository;

/**
 * AssembleeGeneraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssembleeGeneraleRepository extends \Doctrine\ORM\EntityRepository
{

	public function findNextBySection($section){
		$qb = $this->createQueryBuilder('ag');
		$result = $qb
			->select('ag')
			->where('ag.section = :p_section')
			->andwhere('ag.date > :p_date')
			->orderby('ag.date','ASC')
			->setParameters(array('p_section'=>$section,'p_date'=> new \DateTime()))
            ->setMaxResults(1)
			->getQuery()
    		->execute();

        return sizeof($result)?$result[0]:null;
	}


	public function findAGs($annee,$numTrimestre){
		
		if(!$numTrimestre){
			$numTrimestre = 1;
		}
		
		switch ($numTrimestre) {
			case 1:
				$params = array(
					'p_debut'=> new \DateTime($annee.'-04-01'),
					'p_fin'=> new \DateTime($annee.'-06-30'),
					);
				break;
			case 2:
				$params = array(
					'p_debut'=> new \DateTime($annee.'-07-01'),
					'p_fin'=> new \DateTime($annee.'-09-30'),
					);
				break;
			case 3:
				$params = array(
					'p_debut'=> new \DateTime($annee.'-10-01'),
					'p_fin'=> new \DateTime($annee.'-12-31'),
					);
				break;
			case 4:
				$params = array(
					'p_debut'=> new \DateTime(($annee+1).'-01-01'),
					'p_fin'=> new \DateTime(($annee+1).'-03-31'),
					);
				break;
			default:
				case 1:
				break;
		}

		$qb = $this->createQueryBuilder('assembleeGenerale');
		$result = $qb
			->select('assembleeGenerale')
			->where('assembleeGenerale.date >= :p_debut')
			->andwhere('assembleeGenerale.date <= :p_fin')
			->setParameters($params)
			->getQuery()
    		->execute();

        return $result;
	}
}
