<?php

namespace AppBundle\Repository;

/**
 * ContactDiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDiplomeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLastDiplomes($section,$date){
		
		$qb = $this->createQueryBuilder('contactDiplome');
		$result = $qb
			->select('contactDiplome')
			->join('AppBundle:Contact','c','WITH','contactDiplome.contact = c')
			->where('c.section = :p_section')
			->andwhere('contactDiplome.dateObtention >= :p_date')
			->setParameters(array('p_section'=>$section,'p_date'=>$date))
			->getQuery()
    		->execute();

        return $result;
	}
}
