<?php

namespace AppBundle\Repository;

/**
 * ContratPrevObsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratPrevObsRepository extends \Doctrine\ORM\EntityRepository
{
}
