<?php

namespace AppBundle\Repository;

/**
 * ContactDiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDiplomeRepository extends \Doctrine\ORM\EntityRepository
{
}
