<?php

namespace AppBundle\Repository;

/**
 * ContratPrevoyanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratPrevoyanceRepository extends \Doctrine\ORM\EntityRepository
{
}
