<?php

namespace AppBundle\Repository;

/**
 * DestIndivEnvoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestIndivEnvoiRepository extends \Doctrine\ORM\EntityRepository
{
}
