<?php

namespace AppBundle\Repository;

/**
 * DocumentSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
