<?php

namespace AppBundle\Repository;

/**
 * DonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonRepository extends \Doctrine\ORM\EntityRepository
{


	public function findDons($annee,$numTrimestre){
		
		if(!$numTrimestre){
			$numTrimestre = 1;
		}

		switch ($numTrimestre) {
			case 1:
				$params = array(
					'p_debut'=> (new \DateTime(($annee-1).'-12-11'))->format('Y/m/d'),
					'p_fin'=> (new \DateTime($annee.'-03-20'))->format('Y/m/d'),
					);
				break;
			case 2:
				$params = array(
					'p_debut'=> (new \DateTime($annee.'-03-21'))->format('Y/m/d'),
					'p_fin'=> (new \DateTime($annee.'-06-20'))->format('Y/m/d'),
					);
				break;
			case 3:
				$params = array(
					'p_debut'=> (new \DateTime($annee.'-06-21'))->format('Y/m/d'),
					'p_fin'=> (new \DateTime($annee.'-09-20'))->format('Y/m/d'),
					);
				break;
			case 4:
				$params = array(
					'p_debut'=> (new \DateTime($annee.'-9-21'))->format('Y/m/d'),
					'p_fin'=> (new \DateTime($annee.'-12-10'))->format('Y/m/d'),
					);
				break;
			default:
				case 1:
				break;
		}

		$qb = $this->createQueryBuilder('don');
		$result = $qb
			->select('don')
			->where('don.dateSaisie >= :p_debut')
			->andwhere('don.dateSaisie <= :p_fin')
			->andwhere('don.isAnonyme != true')
			->setParameters($params)
			->getQuery()
    		->execute();

        return $result;
	}
}
