<?php

namespace AppBundle\Repository;

/**
 * EffectifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EffectifRepository extends \Doctrine\ORM\EntityRepository
{
}
