<?php

namespace AppBundle\Repository;

/**
 * EnvoiRentierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvoiRentierRepository extends \Doctrine\ORM\EntityRepository
{
}
