<?php

namespace AppBundle\Repository;

/**
 * EnvoiRentierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvoiRentierRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLastAnnee(){
		$qb = $this->createQueryBuilder('envoiRentier');
		$result = $qb
			->select('MAX(envoiRentier.annee)')
			->getQuery()
    		->execute();

        return $result[0][1];
	}

	public function findLastTrimestre($annee){
		$qb = $this->createQueryBuilder('envoiRentier');
		$result = $qb
			->select('MAX(envoiRentier.numTrimestre)')
			->where('envoiRentier.annee = :annee')
			->setParameters(array('annee'=>$annee))
			->getQuery()
    		->execute();

        return $result[0][1];
	}

}
