<?php

namespace AppBundle\Repository;

/**
 * FiltrePersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltrePersoRepository extends \Doctrine\ORM\EntityRepository
{
}
