<?php

namespace AppBundle\Repository;

/**
 * FiltreValeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltreValeurRepository extends \Doctrine\ORM\EntityRepository
{
}
