<?php

namespace AppBundle\Repository;

/**
 * FonctionGroupementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionGroupementRepository extends \Doctrine\ORM\EntityRepository
{
}
