<?php

namespace AppBundle\Repository;

use AppBundle\Utils\Tools;

/**
 * FonctionSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionSectionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findWithCap($label){

		$qb = $this->createQueryBuilder('fonctionSection');
		$qb
			->select('fonctionSection')
			->where('fonctionSection.label LIKE :label')
			->setParameters(array('label'=>strtoupper(Tools::stripAccents($label))));

		$query = $qb->getQuery();

        return $query->setMaxResults(1)->getOneOrNullResult();
	}
}
