<?php

namespace AppBundle\Repository;

/**
 * FonctionSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
