<?php

namespace AppBundle\Repository;

/**
 * OffreDecouverteEnvoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreDecouverteEnvoiRepository extends \Doctrine\ORM\EntityRepository
{
}
