<?php

namespace AppBundle\Repository;

/**
 * OrganismeEnvoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismeEnvoiRepository extends \Doctrine\ORM\EntityRepository
{
}
