<?php

namespace AppBundle\Repository;

/**
 * PatrimoineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatrimoineRepository extends \Doctrine\ORM\EntityRepository
{
}
