<?php

namespace AppBundle\Repository;

/**
 * PermissionRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
