<?php

namespace AppBundle\Repository;

/**
 * PouvoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PouvoirRepository extends \Doctrine\ORM\EntityRepository
{
}
