<?php

namespace AppBundle\Repository;

/**
 * RegimeAffiliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegimeAffiliationRepository extends \Doctrine\ORM\EntityRepository
{
}
