<?php

namespace AppBundle\Repository;

/**
 * RemiseTimbreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemiseTimbreRepository extends \Doctrine\ORM\EntityRepository
{
}
