<?php

namespace AppBundle\Repository;

/**
 * StatutMatrimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutMatrimonialRepository extends \Doctrine\ORM\EntityRepository
{
}
