<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByContact($contact,$nb=5){

		$qb = $this->createQueryBuilder('suivi');
		$qb
			->select('suivi')
			->where('suivi.isOk = 0')
			->andwhere('suivi.contact = :contact')
			->leftjoin('AppBundle:Dossier', 'd', 'WITH', 'suivi.dossier = d')
			->setParameters(array('contact'=>$contact))
            ->setFirstResult(0)
            ->setMaxResults($nb);

        $pag = new Paginator($qb);
        return $pag;
	}

	public function findAllByContact($contact){

		$qb = $this->createQueryBuilder('suivi');
		$qb
			->select('suivi')
			->where('suivi.contact = :contact')
			->leftjoin('AppBundle:Dossier', 'd', 'WITH', 'suivi.dossier = d')
			->setParameters(array('contact'=>$contact));

        return $qb->getQuery()->execute();
	}
}
