<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * SuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByDossier($contact,$isOk=false,$nb=false){

		$qb = $this->createQueryBuilder('suivi');
		$qb
			->select('suivi')
			->leftjoin('AppBundle:Dossier', 'd', 'WITH', 'suivi.dossier = d')
			->where('d.contact = :contact')
			->orderBy('suivi.dateCreation','ASC')
			->setParameters(array('contact'=>$contact));

		if(!$isOk){
			$qb->andwhere('suivi.isOk = 0');
		}

		if ($nb){
            $qb->setFirstResult(0);
            $qb->setMaxResults($nb);
		}

        return $qb->getQuery()->execute();
	}
}
