<?php

namespace AppBundle\Repository;

/**
 * TypeOrganismeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOrganismeRepository extends \Doctrine\ORM\EntityRepository
{
}
