<?php

namespace AppBundle\Repository;

/**
 * TypeTourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTourneeRepository extends \Doctrine\ORM\EntityRepository
{
}
