<?php

namespace AppBundle\Repository;

/**
 * VignetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VignetteRepository extends \Doctrine\ORM\EntityRepository
{
}
